### ISSUE TITLE
[ComputationalTool] - Create plugin for COVID-19 tools from bio.tools

### ISSUE THREAD

**Issue by gtsueng** [outbreak-info/outbreak.info-resources#187]
Outbreak.info now has its own ComputationalTool schema viewable at https://discovery.biothings.io/view/outbreak/ComputationalTool. The schema was based off of the bioschemas ComputationalTool profile, which means that it should be straightforward to transform computational tools from bioschemas json to something suitable for outbreak.

To create the plugin:
 **-Step 1: Pull COVID-19-related biotools IDs from their API**
  --https://bio.tools/api/t?page=1&q=COVID-19&sort=score
  --https://bio.tools/api/t?format=json&page=1&q=COVID-19&sort=score
 **-Step 2: Pull bioschemas-formatted metadata from Github**
  --URL for all various formats of the metadata:
   ---https://github.com/bio-tools/content/tree/master/data/
  --Example URL for the bioschemas-formatted metadata for the covid-19-cg tool
   ---https://github.com/bio-tools/content/blob/master/data/covid-19-cg/covid-19-cg.bioschemas.jsonld
  --URL structure for the bioschemas-formatted jsonld 
   ---base = https://github.com/bio-tools/content/blob/master/data/
   ---biotoolsID = covid-19-cg
   ---github directory = base + biotoolsID
   ---bioschemasjson = github directory + biotoolsID.bioschemas.jsonld

**Comment by flaneuse** [comment]
Might also consider how this relates to the [SoftwareSourceCode](https://outbreak.info/resources/search?q&filter=%40type%3ASoftwareSourceCode&page=0&size=10&sort=) entries in outbreak already from Zenodo, Figshare.

I guess ComputationalTool = reusable protocol and SoftwareSourceCode = more one-off scripts?

**Comment by gtsueng** [comment]
There are only 7 Figshare entries of type SoftwareSourceCode in outbreak.info right now. So writing a script would be a waste of effort. It would make more sense to just to change the mapping in the figshare parser from `"software": "SoftwareSourceCode"` to `"software": "ComputationalTool"`.

Zenodo has ~185 SoftwareSourceCode entries in outbreak.info currently. Might make sense for the crawler to treat these differently if the crawler treats publications differently. Otherwise, it would just be a change to the mapping similar to Figshare.

**Comment by gtsueng** [comment]
This bio.tools data will be ingested from NDE
