### ISSUE TITLE
[PUBLICATION, ANALYSIS] Write Imperial College Parser

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info-resources#98]
1. Crawl [Imperial College website](http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/) to get all COVID-related resources.
2. Classify each resource as a `@type`: Publication, Dataset, Analysis, Protocol, SoftwareSourceCode, ImageObject, MediaObject

| Imperial Category | url | outbreak @type |
| - | - | - |
| Reports | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-reports/ | Publication |
| Publications | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-publications/ | DO NOT ADD (covered in "Reports") |
| Planning Tools | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-planning-tools/ | Analysis |
| "Code & Data" | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-scientific-resources/ | Dataset, SoftwareSourceCode (2 entries) |
| " Data" | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-scientific-resources/ | Dataset |
| "Population survey" | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-scientific-resources/ | Protocol |
| Video updates | http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-video-updates/ | DO NOT ADD |

3. Map each property to [outbreak schema](https://github.com/SuLab/outbreak.info-resources/tree/master/yaml)

4. tag with `curatedBy`:
```
curatedBy: {'@type': 'Organization',
'identifier': 'imperialcollege',
 'url': 'http://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-23-united-states/',  // link to original metadata page on site
 'name': 'Imperial College London',
 'updatedDate': <date accessed, in YYYY-MM-DD>}
```

5. If possible, add a [topicCategory](https://github.com/SuLab/outbreak.info-resources/blob/master/covid_topic_categories.tsv) for each resource
6. Deploy to Biothings Hub to add to api.outbreak.info/resources

**Comment by gtsueng** [comment]
https://github.com/gtsueng/covid_imperial_college
